### ISSUE TITLE
Migration to Gen?

### ISSUE THREAD

**Issue by fplk** [probmods/probmods2#116]
Could you briefly comment on what Gen means for this book? Will WebPPL and Gen coexist / be developed in parallel or will a third edition of this book migrate to Gen? If so, is there any ETA for a Gen version?

Thank you in advance.

**Comment by ngoodman** [comment]
Thanks for the question. We have no current plans to migrate to any of the more active PPLs (Gen, Pyro, etc). WebPPL still serves the main purposes of this book very well! I can imagine that changing down the road.
