### ISSUE TITLE
Clarify model criticism section in bayesian data analysis chapter 

### ISSUE THREAD

**Issue by marekjg** [probmods/probmods2#127]
Hi, I'm going through the book and the first thing I've encountered that seems a bit confusing is the part where we split model prediction for each outcome, tournament and pattern:
```
var itemInfo = {pattern: pattern, tournament: tournament, outcome: outcome}
var itemData = _.filter(towData, itemInfo)
var predicted_y = b0 + itemData[0]["nWins"]*b1
```
While itemData contains ~30 entries, with different participants ID, we take `itemData[0]["nWins"]` as a representative. I think that clarifying what pattern means would be beneficial for comprehension, because from the inference side everything is clear.

**Comment by ngoodman** [comment]
thanks! that chapter has been pretty completely revised, so i'm hoping this is not an issue any more.
