### ISSUE TITLE
fix nested inference models

### ISSUE THREAD

**Issue by hawkrobe** [probmods/probmods2#14]
a few of the more complex social inference models in Chap. 6 are giving trouble: you can't enumerate for the inner inference because of the continuous dirichlet samples, and it takes too long to build it every time with MCMC or rejection.

You could cache the inner inference, but a couple of the arguments are functions and even if you refactored it to construct the functions inside the inner inference, the relevant parameters are floats so caching wouldn't even help that much. Is this a case where variational would save us, or am I missing some bad inefficiency?

https://probmods.org/v2/chapters/06-inference-about-inference.html#epistemic-states

Meta-note: This is maybe the most interesting disadvantage i've seen compared to Church's `rejection-query` implementation, since there you can just directly take samples from the inner distribution without needing to first construct a reasonably representative distribution object.

**Comment by ngoodman** [comment]
i've cleaned these up, and all seem to be working!
