### ISSUE TITLE
Unify labeling of localPrototype and globalPrototype in Hierarchical models chapter

### ISSUE THREAD

**Issue by mhtess** [probmods/probmods2#30]
Currently, the first code box uses the variable `bagToPrototype` to refer to the local prototype of the bag.

Code box 2, changes this to `colorProb` (and drops the prototype label)

Code box 3, `prototype` comes back but now refers to the global prototype.
From there on out, it looks like `prototype` refers to the global prototype

**Comment by ngoodman** [comment]
cleaned up.
