### ISSUE TITLE
Drop `justSample` option after upgrading to webppl 0.9.6

### ISSUE THREAD

**Issue by null-a** [probmods/probmods2#31]
Once probmods is running on webppl 0.9.6, the `justSample` can be safely dropped (from [here](https://github.com/probmods/probmods2/search?utf8=✓&q=justSample)). This is because the `samples` property is now *always* available on the marginal returned by sampling based algos, and the `justSample` option has no effect. See probmods/webppl#712.

**Comment by hawkrobe** [comment]
Thanks for the heads-up! I can take care of this.

**Comment by longouyang** [comment]
FYI, I just upgraded webppl to 0.9.6

**Comment by hawkrobe** [comment]
fixed in be7012e273027ecb856a36048547216dbba98f0b
