### ISSUE TITLE
Questions concerning 'Prelude: Thinking About Assembly Lines'

### ISSUE THREAD

**Issue by CMoebus** [probmods/probmods2#51]
Hi,
I have three questions. 
- First, what does it mean to be a 'bad' widget? Is it a widget above or below a threshold ? 
- Second, what is picked from the assembly line ? The good or the bad widget ? Or vice versa, what is left on the assembly line? The bad or the good widget ?
- Third, what is the logic of the array three ascending thresholds in 'condition(_.isEqual([.6, .7, .8], goodWidgetSeq)'. Wouldn't it be better to ask whether all elements in goodWidgetSeq would be greater than the sampled threshold ?
Best, Claus

**Comment by null-a** [comment]
Since I looked at this yesterday, I'll share my understanding:

> what does it mean to be a 'bad' widget?

A widget is represented by a real number. If this real number is greater than the threshold the widget is good, otherwise it's bad.

> what is picked from the assembly line

The factory (`makeWidgetSeq`) rejects bad widgets, only good widgets are included in the factory's output (the returned array).

> what is the logic of the array three ascending thresholds in 'condition(_.isEqual([.6, .7, .8], goodWidgetSeq)'

These represent 3 (good) widgets that have been observed coming out of the factory. From this (and the prior) we want to infer the threshold.

**Comment by CMoebus** [comment]
Hi Paul,
Thanks for the clarification! I had a bit different prior understanding the situation. Especially, that there is only one (!) good sequence of widgets observed.
Best, Claus

https://www.uni-oldenburg.de/en/lcs/

Von: null-a<mailto:notifications@github.com>
Gesendet: Donnerstag, 4. Januar 2018 15:23
An: probmods/probmods2<mailto:probmods2@noreply.github.com>
Cc: Prof. Dr. Claus Möbus<mailto:claus.moebus@uni-oldenburg.de>; State change<mailto:state_change@noreply.github.com>
Betreff: Re: [probmods/probmods2] Questions concerning 'Prelude: Thinking About Assembly Lines' (#51)


Since I looked at this yesterday, I'll share my understanding:

what does it mean to be a 'bad' widget?

A widget is represented by a real number. If this real number is greater than the threshold the widget is good, otherwise it's bad.

what is picked from the assembly line

The factory (makeWidgetSeq) rejects bad widgets, only good widgets are included in the factory's output (the returned array).

what is the logic of the array three ascending thresholds in 'condition(_.isEqual([.6, .7, .8], goodWidgetSeq)'

These represent 3 (good) widgets that have been observed coming out of the factory. From this (and the prior) we want to infer the threshold.

-

**Comment by hawkrobe** [comment]
I'm going to close this for now -- feel free to open a new issue if you have additional questions or comments!
