### ISSUE TITLE
Code for de Finetti's theorem doesn't work

### ISSUE THREAD

**Issue by jkhartshorne** [probmods/probmods2#57]
As far as I can tell, this gives an error:

> var latent = sample(latentPrior)
> var thunk = function() {return observe(latent)}
> var sequence = repeat(2,thunk)

In particular, the error I get is "sample() expected a distribution". I'm confused by this, because I was under the impression that Gaussian() was a distribution!

Interestingly, what is highlighted is the _observe_ function, not _sample_. Not sure what that means.

**Comment by longouyang** [comment]
That example isn't meant to be runnable -- `latentPrior` is actually undefined, so this code *should* give you an error.

For me, `sample` is highlighted, not `observe`. There might be some issue with the error handling code or the editor -- what browser are you using?

**Comment by jkhartshorne** [comment]
I’m using Chrome.
Josh

**Comment by longouyang** [comment]
What version?

**Comment by jkhartshorne** [comment]
Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by longouyang** [comment]
Hmm, me too, but I can't reproduce the highlighting behavior you're getting.
