### ISSUE TITLE
DPmem in "Non-parametric models"

### ISSUE THREAD

**Issue by jamescheney** [probmods/probmods2#65]
In the "Non-parametric models" chapter, in section "Properties of DP Memoized Procedures", the two examples with code

```
var memoizedGaussian = DPmem(1, gaussian);
viz(repeat(10000, function() {return memoizedGaussian(0,1)}));
```

```
var memoizedGaussian = DPmem(1, gaussian);
viz(repeat(10000, function() {return gaussian(0, 1)}));
viz(repeat(10000, function() {return memoizedGaussian(0,1)}));
```

do not work since `DPmem` is undefined.  Copying the code for `DPmem` from the previous examples doesn't seem to do the right thing: the graph resulting from the 

```
viz(repeat(10000, function() {return memoizedGaussian(0,1)}));
```

line produces a graph with a single bar assigning all probability to `null`.

**Comment by ngoodman** [comment]
thanks! i'll look into that as i clean things up (over the next month)...
