### ISSUE TITLE
fix exercises & links to exercises

### ISSUE THREAD

**Issue by hawkrobe** [probmods/probmods2#7]

**Comment by longouyang** [comment]
Temporary fix in a78119df6b7add7349d0bd096820bbd877556883: hide the exercises from table of contents but link to them from individual chapters.

Ideally, though, we'd like exercises to appear as links attached to particular chapters.

**Comment by hawkrobe** [comment]
Since your fix is totally sufficient for course functionality, I think it's fair to close this -- might open up a more specific issue for the nicer infrastructure if it becomes unworkable for some reason
