### ISSUE TITLE
fix BDA chapter

### ISSUE THREAD

**Issue by hawkrobe** [probmods/probmods2#80]
after moving earlier in the book, some major revisions are in order (consolidating Noah's comments in chapter markdown with other comments):
* [x] remove or move+shorten the spinning coin stuff, which is mostly about cogitive models and then bda of cognitive models.
* [x] start with the existing simple models illustrating the kinds of questions one asks with BDA and the metrics for answers (BF, CI, etc)
* [x] then do a slightly more complex model: regression analysis.
* [x] then do BDA of cognitive models.
* [ ] then do full tug-of-war example. needs to be cleaned up for clarity.
* [ ] consider splitting into two chapters, with model selection stuff in part 2 occurring after occam's razor chapter. LMER models also make more sense there....
* [x] need to add some discussion of CIs.
* [x] Include illustrations of each point with regression models, as wel as simpler models that are there now.
* [ ] include some discussion of contamination models and other stadard BDA model idioms.
* [x] most of the editor.put and .get things are unecessary?
* [x] the data munging is pretty crazy. use more standard DF library?
* [x] dist.MAP() seems suspect....
* [ ] the BDA of tug-of-war model is too complex and inefficient to be run effectively in the browser and could use either some optimization, or a simpler pedagogical case (with a pointer to the Rwebppl file for the more thorough model).
* [x] posterior predictive checks are not very well explained -- need to show an example of a good result, not just the bad one. (also having only two data points makes it hard to understand the scatter plot...)

**Comment by ngoodman** [comment]
chapter substantially revised. it would still be helpful to flesh out the bda of cogn models part, and add some "standard modeling components for bda". those are different enough that i'm closing this issue now!
